services:
  - type: web
    name: scraper
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser chromium-driver
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    autoDeploy: false
